### ISSUE TITLE
Please specify a blanket licence, so I can package this repo for mageia and fedora

### ISSUE THREAD

**Issue by shlomif** [JKirchartz/fortune#1]
Hi!

See https://github.com/shlomif/Freenode-programming-channel-FAQ/blob/master/FAQ_with_ToC__generated.md#i-want-to-release-my-code---which-open-source-licence-should-i-use .

Thanks in advance.

**Comment by JKirchartz** [comment]
I've added the public domain Unlicense - I hope this is acceptable for packaging.

**Comment by shlomif** [comment]
On Thu, 09 Apr 2020 11:15:58 -0700
Joel Kirchartz <notifications@github.com> wrote:

> I've added the public domain Unlicense - I hope this is acceptable for
> packaging.
> 

Thanks, Joel!

It should be based on https://fedoraproject.org/wiki/Licensing/Unlicense and
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing .

Regards,

	Shlomi Fish

-- 

Shlomi Fish       https://www.shlomifish.org/
The Human Hacking Field Guide - https://shlom.in/hhfg

Katie: in case you have any interest in me, I should note that I have a policy
against getting involved with people who are 4 times my senior or more.
    — https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/

Please reply to list if it's a mailing list post - https://shlom.in/reply .
